version: '3.1'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            KAFKA_CREATE_TOPICS: "logs:3:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    publisher:
        build:
            context: ./docker
            dockerfile: PhpDockerfile
        volumes:
            - ./src:/var/www/app

    consumer1:
        build:
            context: ./docker
            dockerfile: PhpDockerfile
        environment:
            SERVICE_ROLE: "Consumer1"
        volumes:
            - ./src:/var/www/app
        command: ./start.sh

    consumer2:
        build:
            context: ./docker
            dockerfile: PhpDockerfile
        environment:
            SERVICE_ROLE: "Consumer2"
        volumes:
            - ./src:/var/www/app
        command: ./start.sh

    web:
        build:
            context: ./docker
            dockerfile: WebDockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/app
